baseurl = "/"
languageCode = "en-us"
title = "ABCD Workshop on Brain Development and Mental Health"
theme = "hugo-theme-casper"
# disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 1
canonifyurls = true
data-netlify="true"

[params]
  description = "Sponsored by the NIMH<br>Location: Portland, Oregon<br>Dates: August 19-23, 2019<br><br>Sign up to receive updates"
  cover = "images/cover.jpg"
  googleAnalyticsUserID = ""
  hideHUGOSupport = false